# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["{{elastic_protocol}}://localhost:{{elastic_port}}"]
  username: "{{remote_monitoring_user_username}}"
  password: "{{remote_monitoring_user_password}}"

