# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: ["localhost:{{kibana_port}}"]
  #basepath: ""
  username: "{{remote_monitoring_user_username}}"
  password: "{{remote_monitoring_user_password}}"
