---

# This playbook  will deploy wbeserver
- hosts: all
  become: yes
  roles:
  - ../roles/add-elastic-repo

# This playbook  will deploy elk stack
- hosts: elk
  become: yes
  vars_files: 
  - ../vars/credentials.yml
  - ../vars/main.yml

  roles:
  - ../roles/elasticsearch
  - ../roles/kibana

  
  # This playbook  will deploy wbeserver
- hosts: webservers
  become: yes
  vars_files: 
  - ../vars/credentials.yml
  - ../vars/main.yml

  roles:
  - ../roles/webserver
