---
# This playbook  will deploy wbeserver
- hosts: webservers
  become: yes
  vars_files: 
  - ../vars/credentials.yml
  - ../vars/main.yml

  roles:
  - ../roles/webserver
  - ../roles/metricbeat
  - ../roles/filebeat
  - ../roles/auditbeat
  - ../roles/packetbeat
  - ../roles/config-beats-webserver